### ISSUE TITLE
"cannot import name '_validate_lengths' "

### ISSUE THREAD

**Issue by bemoregt** [javiribera/locating-objects-without-bboxes#40]
HI, @chenyuhao @javiribera @dguera 

I met this error when run your elvaluation script.

"cannot import name '_validate_lengths' "

I installed your conda  install guide ...
 
What's wrong to me ?

Thanks.
Best,

@bemoregt.

**Comment by javiribera** [comment]
Please provide the full stack traceback

**Comment by bemoregt** [comment]
Hi, @javiribera, @chenyuhao @dguera  

It is may be a 'peterpy' package install problems. 

It is so hard to install that package. 

Best.
Thanks. 
@bemoregt.

**Comment by javiribera** [comment]
I won't be able to help without the entire error stack.

**Comment by emergencyd** [comment]
you should just google this error. You will find out that you just need to downgrade your numpy version @bemoregt

**Comment by Aichiimv** [comment]
`pip install -U scikit-image ` worked for me

**Comment by policheh** [comment]
Hi @javiribera ,
the same for me. Full stack:

python -m object-locator.train -h
Traceback (most recent call last):
  File ".conda/envs/object-locator/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File ".conda/envs/object-locator/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "locating-objects-without-bboxes/object-locator/train.py", line 40, in <module>
    import skimage.transform
  File ".conda/envs/object-locator/lib/python3.6/site-packages/skimage/__init__.py", line 158, in <module>
    from .util.dtype import *
  File ".conda/envs/object-locator/lib/python3.6/site-packages/skimage/util/__init__.py", line 7, in <module>
    from .arraycrop import crop
  File ".conda/envs/object-locator/lib/python3.6/site-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'

Thanks.

Best regards,
Boris
