### ISSUE TITLE
About the XML file about the groundtruth

### ISSUE THREAD

**Issue by yanbai1993** [javiribera/locating-objects-without-bboxes#7]
Hi sir,
I want to train the model in mall dataset with your code.
After downloading the dataset, the GT file is a mat format.
Can you provide the XML file for each dataset?

The error log is ：
(object-locator) imre@imre2018-09-01:~/baiyan/locating-objects-without-bboxes$ python -m object-locator.train    --train-dir ./mall_dataset/frames/        --batch-size 32        --visdom-env sorghum        --lr 1e-3        --val-dir ./mall_dataset/frames/        --optim Adam        --save saved_model.ckpt
W: Not connected to any Visdom server. You will not visualize any training/validation plot or intermediate image
W: The dataset directory ./mall_dataset/frames/ does not contain a XML file with groundtruth. Metrics will not be evaluated.Only estimations will be returned.
Traceback (most recent call last):
  File "/home/imre/anaconda2_v2/envs/object-locator/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/imre/anaconda2_v2/envs/object-locator/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/imre/baiyan/locating-objects-without-bboxes/object-locator/train.py", line 93, in <module>
    max_valset_size=args.max_valset_size)
  File "/home/imre/baiyan/locating-objects-without-bboxes/object-locator/data.py", line 131, in get_train_val_loaders
    seed=seed)
  File "/home/imre/baiyan/locating-objects-without-bboxes/object-locator/data.py", line 66, in build_dataset
    seed=seed)
  File "/home/imre/baiyan/locating-objects-without-bboxes/object-locator/data_plant_stuff.py", line 93, in __init__
    with open(os.path.join(directory, xml_filename), 'r') as fd:
  File "/home/imre/anaconda2_v2/envs/object-locator/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/imre/anaconda2_v2/envs/object-locator/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

**Comment by javiribera** [comment]
Related: https://github.com/javiribera/locating-objects-without-bboxes/issues/10

Please do not use XML files. If you still experience issues with a CSV ground truth file feel free to reopen this issue.

Thanks,
