### ISSUE TITLE
error when install ballpark

### ISSUE THREAD

**Issue by 666xiaohei666** [javiribera/locating-objects-without-bboxes#8]
Collecting ballpark==1.4.0 (from -r /test/locating-objects-without-bboxes-master/condaenv.ivbc642u.requirements.txt (line 1))
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/8f/5b/e259db671525c63202885c2cad5fc90cf095a65149a2ad3a7586fa73180f/ballpark-1.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fxtjjwiz/ballpark/setup.py", line 5, in <module>
        long_description=open('README.rst').read(),
      File "/root/anaconda3/envs/object-locator/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 650: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fxtjjwiz/ballpark/

CondaValueError: pip returned an error

**Comment by javiribera** [comment]
What command did you run to get this error? Please follow the instructions in https://github.com/javiribera/locating-objects-without-bboxes#installation.

Ballpark 1.4.0 seems to be perfectly available at pypi (https://pypi.org/project/ballpark/1.4.0). If you install it via pip you shouldn't be having any issue.

**Comment by javiribera** [comment]
Closing due to inactivity. Anyway this seems like a problem from the ballpark package. Feel free to reopen if this is preventing you from installing the object-locator package.
